USE [master]
GO

/****** Object:  Database [ProjetGestion]    Script Date: 25/11/2018 09:54:32 ******/
CREATE DATABASE [ProjetGestion]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ProjetGestion', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\ProjetGestion.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ProjetGestion_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\ProjetGestion_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [ProjetGestion] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ProjetGestion].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ProjetGestion] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ProjetGestion] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ProjetGestion] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ProjetGestion] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ProjetGestion] SET ARITHABORT OFF 
GO

ALTER DATABASE [ProjetGestion] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ProjetGestion] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ProjetGestion] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ProjetGestion] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ProjetGestion] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ProjetGestion] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ProjetGestion] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ProjetGestion] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ProjetGestion] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ProjetGestion] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ProjetGestion] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ProjetGestion] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ProjetGestion] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ProjetGestion] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ProjetGestion] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ProjetGestion] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ProjetGestion] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ProjetGestion] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ProjetGestion] SET  MULTI_USER 
GO

ALTER DATABASE [ProjetGestion] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ProjetGestion] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ProjetGestion] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ProjetGestion] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [ProjetGestion] SET  READ_WRITE 
GO


